version: "3.3"

services:
  nextcloud-db:
    image: mariadb:10.11.2
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../db-data:/var/lib/mysql
      - ../db-config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PW
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=YOUR_MYSQL_NEXTCLOUD_PW
    networks:
      - nextcloud-network
    restart: unless-stopped

  nextcloud-app:
    build: .
    container_name: nextcloud-app
    depends_on:
      - nextcloud-db
    volumes:
      - ../data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-app.rule=Host(`YOUR_HOSTNAME`)"
      - "traefik.http.routers.nextcloud-app.entrypoints=https"
      - "traefik.http.routers.nextcloud-app.tls.certresolver=le"
      - "traefik.http.routers.nextcloud-app.tls=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nextcloud-app.middlewares=secHeaders@file"
    networks:
      - nextcloud-network
      - traefik
    ports:
      - 8082:80
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=YOUR_MYSQL_NEXTCLOUD_PW
      - MYSQL_HOST=nextcloud-db
    restart: unless-stopped

networks:
  nextcloud-network:
  traefik:
    external: true
