version: "3.3"

services:
  traefik:
    image: "traefik:2.9.5"
    container_name: "traefik"
    # Config implicitly loaded from /etc/traefic/traefic.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - "traefik"
      - "traefik-out"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./letsencrypt:/letsencrypt
      - ./data/dynamic_conf.yml:/dynamic_conf.yml
      - ./data/traefik.yml:/etc/traefik/traefik.yml
      - ./data/access.log:/access.log
    labels:
      - "providers.file.filename=/dynamic_conf.yml"
    restart: unless-stopped

  inner-whoami:
    image: "containous/whoami"
    container_name: "inner-whoami"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      # Get the routes from http
      - "traefik.http.routers.inner-whoami.rule=Host(`YOUR_HOSTNAME`) && Path(`/whoami`)"
      - "traefik.htto.routers.inner-whoami.entrypoints=https"
      - "traefik.http.routers.inner-whoami.tls=true"
      - "traefik.http.routers.inner-whoami.tls.certresolver=le"
    restart: unless-stopped

# Network must be manually created with local IPv6 prefix
# with docker-compose < 1.28
# docker network create --ipv6 --subnet=fd12:3456:789a:2::/64 traefik-out
networks:
    traefik-out:
        enable_ipv6: true
        ipam:
            config:
                - subnet: "fd12:3456:789a:1::/64"
    traefik:
        external: true

